// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyServerClient is the client API for MyServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServerClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloBody, opts ...grpc.CallOption) (*HelloReply, error)
}

type myServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServerClient(cc grpc.ClientConnInterface) MyServerClient {
	return &myServerClient{cc}
}

func (c *myServerClient) SayHello(ctx context.Context, in *HelloBody, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/protoExample.MyServer/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServerServer is the server API for MyServer service.
// All implementations must embed UnimplementedMyServerServer
// for forward compatibility
type MyServerServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloBody) (*HelloReply, error)
	mustEmbedUnimplementedMyServerServer()
}

// UnimplementedMyServerServer must be embedded to have forward compatible implementations.
type UnimplementedMyServerServer struct {
}

func (UnimplementedMyServerServer) SayHello(context.Context, *HelloBody) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedMyServerServer) mustEmbedUnimplementedMyServerServer() {}

// UnsafeMyServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServerServer will
// result in compilation errors.
type UnsafeMyServerServer interface {
	mustEmbedUnimplementedMyServerServer()
}

func RegisterMyServerServer(s grpc.ServiceRegistrar, srv MyServerServer) {
	s.RegisterService(&MyServer_ServiceDesc, srv)
}

func _MyServer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoExample.MyServer/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServerServer).SayHello(ctx, req.(*HelloBody))
	}
	return interceptor(ctx, in, info, handler)
}

// MyServer_ServiceDesc is the grpc.ServiceDesc for MyServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoExample.MyServer",
	HandlerType: (*MyServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _MyServer_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/processor_message.proto",
}
